/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package restoswing;

import java.net.URI;
import java.net.http.*;
// import static restoswing.Commande_liste.API_url;

/**
 *
 * @author antoine
 */
public class Commande_details extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Commande_details.class.getName());
    private int id_commande;
    /**
     * Creates new form Command_details
     */    
    public Commande_details(java.awt.Frame parent, boolean modal, Commande commande) {
        super(parent, modal);
        initComponents();
        
        // ici on remplit la JTable avec les lignes de la commande
        MyTableModel2 model = new MyTableModel2(commande.getLignes());
        jTable1.setModel(model);
        
        String json = "";
        this.id_commande = commande.getIdCommande();
        
        // infos recupérer pour les labels (id commande + date de la commande + login utilisateur
        jLabel2.setText("Détails de la commande n°" + commande.getIdCommande());
        jLabel3.setText("Date: " + commande.getDate_commande());
        jLabel4.setText("Login: " + commande.getLoginUtilisateur());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("RestoSwing");

        jLabel2.setText("Détails de la commande n°");

        jLabel3.setText("Date: ");

        jLabel4.setText("Login:");

        jButton3.setText("Accepter");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Refuser");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton1.setText("Prête");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Revenir aux commandes");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                              
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
        String json = "";
        String API_url = "http://localhost/projet/appRoseBlanche/api/commande_refuser.php?id_commande=" + id_commande;
        
        // créer un http client
        HttpClient client = HttpClient.newHttpClient();
        // créer une requete http GET
        try {
            // construit l'url de la requete 
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(new URI(API_url))
                    .build();
            // envoie la requete et attends la réponse
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            // verifie que le resultat est normale
            if(response.statusCode() == 200){
                json = response.body();
                this.dispose();
            } else{
                System.err.println("Erreur : Code statut " + response.statusCode());
            }
        } catch (Exception ex){
            System.err.println("Erreur : " + ex.getMessage());
            // ex.printStackTrace
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
        String json = "";
        String API_url = "http://localhost/projet/appRoseBlanche/api/commande_accepter.php?id_commande=" + id_commande;
        
        // créer un http client
        HttpClient client = HttpClient.newHttpClient();
        // créer une requete http GET
        try {
            // construit l'url de la requete 
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(new URI(API_url))
                    .build();
            // envoie la requete et attends la réponse
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            // verifie que le resultat est normale
            if(response.statusCode() == 200){
                json = response.body();
                this.dispose();
            } else{
                System.err.println("Erreur : Code statut " + response.statusCode());
            }
        } catch (Exception ex){
            System.err.println("Erreur : " + ex.getMessage());
            // ex.printStackTrace
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String json = "";
        String API_url = "http://localhost/projet/appRoseBlanche/api/commande_terminer.php?id_commande=" + id_commande;
        
        // créer un http client
        HttpClient client = HttpClient.newHttpClient();
        // créer une requete http GET
        try {
            // construit l'url de la requete 
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(new URI(API_url))
                    .build();
            // envoie la requete et attends la réponse
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            // verifie que le resultat est normale
            if(response.statusCode() == 200){
                json = response.body();
                this.dispose();
            } else{
                System.err.println("Erreur : Code statut " + response.statusCode());
            }
        } catch (Exception ex){
            System.err.println("Erreur : " + ex.getMessage());
            // ex.printStackTrace
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // bouton pour revenir à la liste des commandes (on ferme la jdialog)
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
